{
 "title": "JWT-Pizza-Service Metrics pizza-spencer.click",
 "time": { "from": "2025-11-19T05:59:33.702Z", "to": "2025-11-19T06:59:33.702Z" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"http\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Factory Responses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"factory\"} |= `response` | json"
    }
   ]
  },
  {
   "title": "Pizza Factory Responses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"factory\"} |= `request` | json"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"http\", component=\"jwt-pizza-service\"} | json | level = `warn`",
     "maxLines": 200
    }
   ]
  },
  {
   "title": "ErrorLogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"http\", component=\"jwt-pizza-service\"} | json | level = `error` | line_format `path: '{{.path}}', statusCode: {{.statusCode}}, Failure Message: {{.resBody}}`",
     "maxLines": 200
    }
   ]
  },
  {
   "title": "DB Queries",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"db\"} | json | json param_list=\"params\" | line_format `Query Template: {{.query}} | Parameters: {{.param_list}}`",
     "maxLines": 200
    }
   ]
  },
  {
   "title": "Non-200 Status Factory Responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `factory` != `200` |= `response` | json | log = `factory`",
     "maxLines": 200
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revenue_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue / Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Sold / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{pizzaType}}"
    },
    {
     "expr": "rate(failedPizzas_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed Pizzas"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "rate(requestMethods_total{method!=\"all\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Avg Latency Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "request_latency_avg_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_latency_avg_ms_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(allRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Attempts / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "targets": [
    {
     "expr": "rate(authentications_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Total Pizzas Sold",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizzasSold_total{pizzaType=\"all\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pizzas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "failedPizzas_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Valid Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(requestMethods_total{method=\"all\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    { "expr": "rate(chaosUrl_total[15s])", "legendFormat": "{{url}}" }
   ]
  }
 ]
}